# Generated by Django 4.0.4 on 2022-04-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_patronymic_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='Номер квартиры')),
                ('floor', models.IntegerField(blank=True, verbose_name='Этаж')),
                ('total_area', models.FloatField(blank=True, verbose_name='Общая площадь')),
                ('number_of_residents', models.IntegerField(blank=True, verbose_name='Количество проживающих')),
                ('availability_of_underground_parking', models.BooleanField(blank=True, verbose_name='Наличие подземного паркинга')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='flat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.flat', verbose_name='Квартира'),
            preserve_default=False,
        ),
    ]
