# Generated by Django 4.0.4 on 2022-04-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_flat_user_phone_user_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.flat', verbose_name='Квартира'),
        ),
    ]
