# Generated by Django 4.0.4 on 2022-04-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_proxygroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Номер телефона'),
        ),
    ]
