# Generated by Django 4.0.4 on 2022-04-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='availability_of_underground_parking',
            field=models.BooleanField(verbose_name='Наличее подземного паркинга'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number_of_residents',
            field=models.IntegerField(verbose_name='Количество проживающих'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='total_area',
            field=models.FloatField(verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
    ]
