# Generated by Django 4.0.4 on 2022-04-20 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_questionsfromguests'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsfromguests',
            name='contacted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Связались ли с человеком?'),
        ),
        migrations.AddField(
            model_name='questionsfromguests',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='questionsfromguests',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
    ]
