# Generated by Django 4.0.4 on 2022-04-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_meterreadings_cold_water_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_time', models.DateField(verbose_name='Предпочтительное время')),
                ('master', models.CharField(choices=[('1', 'Сантехник'), ('2', 'Электрик')], max_length=25)),
                ('text', models.TextField(verbose_name='Причина вызова')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вызов мастера',
                'verbose_name_plural': 'Вызов мастера',
            },
        ),
    ]
