# Generated by Django 4.0.4 on 2022-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_callingwizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingwizard',
            name='reaction',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пользователь получил ответ на свою заявку?'),
        ),
        migrations.AlterField(
            model_name='callingwizard',
            name='preferred_time',
            field=models.DateField(blank=True, verbose_name='Предпочтительное время'),
        ),
    ]
