# Generated by Django 4.0.4 on 2022-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_callingwizard_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingwizard',
            name='preferred_time',
            field=models.DateTimeField(blank=True, verbose_name='Предпочтительное время'),
        ),
    ]
