# Generated by Django 4.0.4 on 2022-04-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_meterreadings_cold_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callingwizard',
            name='preferred_time',
        ),
    ]
