# Generated by Django 4.0.4 on 2022-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_role_questionsuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsuser',
            options={'verbose_name': 'Вопрос пользователя', 'verbose_name_plural': 'Вопросы пользователя'},
        ),
        migrations.RemoveField(
            model_name='questionsuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='questionsuser',
            name='master',
        ),
        migrations.AddField(
            model_name='questionsuser',
            name='to_whom',
            field=models.CharField(choices=[('1', 'Администратор'), ('3', 'Председатель'), ('3', 'Бухгалтер')], default=1, max_length=25, verbose_name='Кому вопрос?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsuser',
            name='reaction',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пользователь получил ответ на свой вопрос?'),
        ),
        migrations.AlterField(
            model_name='questionsuser',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
