# Generated by Django 4.0.4 on 2022-04-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_remove_advertising_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
