# Generated by Django 4.0.4 on 2022-04-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionForSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('AGREE', 'За'), ('AGAINST', 'Против'), ('HOLD', 'Воздержался')], max_length=300)),
                ('question_for_durvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.questionforsurvey', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.AddField(
            model_name='userquestionforsurvey',
            name='user_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.usersurvey', verbose_name='Опрос'),
        ),
    ]
